Django 수업/Django(5)/01_crud_live_pjt/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
]

Django 수업/Django(5)/01_crud_live_pjt/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

Django 수업/Django(5)/01_crud_live_pjt/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}번째글 - {self.title}'

Django 수업/Django(5)/01_crud_live_pjt/articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'articles/index.html', context)


def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {'article': article}
    return render(request, 'articles/detail.html', context)


def new(request):
    return render(request, 'articles/new.html')


def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    article = Article(title=title, content=content)
    article.save()
    return redirect('articles:index')


def delete(request, pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect('articles:index')


def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {'article': article}
    return render(request, 'articles/edit.html', context)


def update(request, pk):
    article = Article.objects.get(pk=pk)
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    return redirect('articles:detail', pk=article.pk)

Django 수업/Django(5)/01_crud_live_pjt/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>DETAIL</h1>
  <hr>

  <p>글 제목 : {{article.title}}</p>
  <p>글 내용 : {{article.content}}</p>
  <p>생성시각 : {{article.created_at}}</p>
  <p>수정시각 : {{article.updated_at}}</p>

  <hr>
  <a href="{% url 'articles:index' %}">목록보기</a>
  <a href="{% url 'articles:edit' article.pk %}">수정하기</a>
  <form action="{% url 'articles:delete' article.pk %}">
    {% csrf_token %}
    <input type="submit" value="삭제하기">
  </form>
  

{% endblock content %}

Django 수업/Django(5)/01_crud_live_pjt/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}
  <h1>글수정</h1>
  <hr>

  <form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    <label for="title">제목 : </label>
    <input type="text" id="title" name="title" value="{{article.title}}"><br>
    <label for="content">내용 : </label>
    <input type="text" id="content" name="content"value="{{article.content}}"><br>
    <input type="submit">
  </form>

  <hr>
  <a href="{% url 'articles:detail' article.pk %}">돌아가기</a>
{% endblock content %}

Django 수업/Django(5)/01_crud_live_pjt/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>INDEX</h1>
  <a href="{% url 'articles:new' %}">작성하기</a>
  <hr>

  {% for article in articles %}
    <p>글 번호 : {{article.id}}</p>
    <p><a href="{% url 'articles:detail' article.pk %}">글 제목 : {{article.title}}</a></p>
    <p>글 내용 : {{article.content}}</p>
    <hr>
  {% endfor %}

{% endblock content %}

Django 수업/Django(5)/01_crud_live_pjt/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
  <h1>글작성</h1>
  <hr>

  <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    <label for="title">제목 : </label>
    <input type="text" id="title" name="title"><br>
    <label for="content">내용 : </label>
    <input type="text" id="content" name="content"><br>
    <input type="submit">
  </form>
{% endblock content %}