DB 수업/database_05 M;N/01_template/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name="update"),
    path('password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

DB 수업/database_05 M;N/01_template/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/likes/', views.likes, name='likes'),
]

DB 수업/database_05 M;N/01_template/crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DB 수업/database_05 M;N/01_template/articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    title = models.CharField(max_length=30)
    content = models.TextField()
    image = models.ImageField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}번째글 - {self.title}'


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

DB 수업/database_05 M;N/01_template/articles/forms.py
from django import forms
from .models import Article, Comment

# class ArticleForm(forms.Form):
#     title = forms.CharField(max_length=30)
#     content = forms.CharField(widget=forms.Textarea)


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        # fields = '__all__'
        exclude = (
            'user',
            'like_users',
        )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        # fields = '__all__'
        exclude = (
            'article',
            'user',
        )

DB 수업/database_05 M;N/01_template/articles/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from .models import Article, Comment
from .forms import ArticleForm, CommentForm

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'articles/index.html', context)


def detail(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm()
    comments = article.comment_set.all()
    context = {
        'article': article,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'articles/detail.html', context)


def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()

    context = {'form': form}
    return render(request, 'articles/create.html', context)


def delete(request, pk):
    article = Article.objects.get(pk=pk)
    if request.user == article.user:
        article.delete()
        return redirect('articles:index')
    return redirect('articles:detail', article.pk)


def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.user == article.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:detail', pk=article.pk)
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:detail', article.pk)
    context = {'form': form, 'article': article}
    return render(request, 'articles/update.html', context)


def comments_create(request, pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')

    article = Article.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.user = request.user
        comment.save()
    return redirect('articles:detail', article.pk)


def comments_delete(request, pk, comment_pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect('articles:detail', pk)


@require_POST
def likes(request, article_pk):
    if request.user.is_authenticated:
        article = Article.objects.get(pk=article_pk)
        if article.like_users.filter(pk=request.user.pk).exists():
            article.like_users.remove(request.user)
        else:
            article.like_users.add(request.user)
        return redirect('articles:index')
    return redirect('accounts:login')

DB 수업/database_05 M;N/01_template/articles/templates/articles/create.html
{% extends 'base.html' %} 

{% block content %}
  <h1>글작성</h1>
  <hr />

  <form
    action="{% url 'articles:create' %}"
    method="POST"
    enctype="multipart/form-data">
    {% csrf_token %} {{form.as_p}}
    <input type="submit" value="작성하기"/>
  </form>

  <br />
  <hr>
  <a href="{% url 'articles:index' %}">목록보기</a>
{% endblock content %}

DB 수업/database_05 M;N/01_template/articles/templates/articles/detail.html
{% extends 'base.html' %} 

{% block content %}
  <h1>DETAIL</h1>
  <hr />

  {% if article.image %}
    <img src="{{article.image.url}}" />
  {% endif %}

  <div id="article-content">
    <p>글 제목 : {{article.title}}</p>
    <p>글 내용 : {{article.content}}</p>
    <p>작성자 : {{article.user}}</p>
    <p>생성시각 : {{article.created_at}}</p>
    <p>수정시각 : {{article.updated_at}}</p>
    <hr>

    {% if request.user == article.user %}
      <a href="{% url 'articles:update' article.pk %}">수정하기</a>
      <form action="{% url 'articles:delete' article.pk %}" id="delete-form">
        {% csrf_token %}
        <input type="submit" value="삭제하기" id="delete-btn" />
      </form><br>
      <hr>
    {% endif %}
    
    <a href="{% url 'articles:index' %}">목록보기</a>
    <br><br>
    <h5>Comments</h5>
    <hr>
    {% if comments %}
      <p><b>{{comments|length}}개의 댓글</b></p>
    {% endif %}

    <ul>
      {% for comment in comments %}
        <li>
          {{comment.content}} - {{comment.user}}
          {% if request.user == comment.user %}
            <form action="{% url 'articles:comments_delete' article.pk comment.pk%}" method="POST">
              {% csrf_token %}
              <input type="submit" value="삭제">
            </form>
          {% endif %}
        </li>
      {% empty %}
        <li>댓글이 없습니다 :(</li>
      {% endfor %}
    </ul>
    
    {% if request.user.is_authenticated %}
      <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
        {% csrf_token %}
        {{comment_form}}
        <input type="submit" value="저장">
      </form>
    {% else %}
      <a href="{% url 'accounts:login' %}">댓글 달려면 로그인 하라구!</a>
    {% endif %}

  </div>
{% endblock content %}

DB 수업/database_05 M;N/01_template/articles/templates/articles/index.html
{% extends 'base.html' %} 

{% block content %}
  <h1>INDEX</h1>
  <a href="{% url 'articles:create' %}">작성하기</a>
  <hr />

  {% for article in articles %}
    <p>
      [{{article.id}}] 
      <a href="{% url 'articles:detail' article.pk %}" id="article-title">{{article.title}}</a>
      - 작성자: <a href="{% url 'accounts:profile' article.user.username %}">{{article.user}}</a> 
    </p>
    {% if request.user.is_authenticated %}
      <div>
        <form action="{% url 'articles:likes' article.pk %}" method="POST">
          {% csrf_token %}
          {% if request.user in article.like_users.all %}
            <input type="submit" value="안좋아해!">
          {% else %}
            <input type="submit" value="좋아해!">
          {% endif %}
        </form>
      </div>
    {% endif %}
    <hr />
  {% endfor %} 

{% endblock content %}

DB 수업/database_05 M;N/01_template/articles/templates/articles/update.html
{% extends 'base.html' %} 

{% block content %}
  <h1>글수정</h1>
  <hr />

  <form action="{% url 'articles:update' article.pk %}" method="POST"  enctype='multipart/form-data'>
    {% csrf_token %} {{form.as_p}}
    <input type="submit" />
  </form>

  <hr />
  <a href="{% url 'articles:detail' article.pk %}">돌아가기</a>
{% endblock content %}